# Generated by Django 2.2.16 on 2020-11-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('notes', models.CharField(max_length=750)),
                ('cook_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Cookbook')),
            ],
        ),
    ]
