# Generated by Django 3.1.5 on 2021-05-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetype',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_types',
            field=models.ManyToManyField(to='recipe.RecipeType'),
        ),
    ]
