# Generated by Django 3.1.3 on 2020-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetype',
            name='recipes',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
    ]
