# Generated by Django 4.1.2 on 2022-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
