# Generated by Django 4.1.2 on 2022-10-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_cookbook_author'),
        ('recipe', '0002_alter_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.cookbook'),
        ),
    ]
