# Generated by Django 3.2.16 on 2023-12-10 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_cook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='user_name',
            field=models.CharField(default='-nouser-', max_length=25),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
