# Generated by Django 4.2.11 on 2024-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20231210_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url_ref',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
