# Generated by Django 4.2.11 on 2024-12-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_url_ref_alter_recipe_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
