# Generated by Django 2.2.16 on 2020-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='publish_date',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
