# Generated by Django 4.1.2 on 2022-10-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_author_id_alter_cookbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.author'),
        ),
    ]
