# Generated by Django 3.1.3 on 2020-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='meal',
            name='was_made',
            field=models.BooleanField(default=False),
        ),
    ]
