# Generated by Django 4.1.2 on 2022-11-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='note',
            new_name='notes',
        ),
    ]
