# Generated by Django 3.1.3 on 2021-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20201210_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='note',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
